### ISSUE TITLE
Migration conflict on app restart

### ISSUE THREAD

**Issue by dpiliouras** [weavejester/ragtime#144]
Hi there, 

I am using this via the `duct.migrator/ragtime` key.  I've created the `schema.up/down.sql` files and when the app starts the very first time, the migration is applied (and recorded in the DB) successfully. However, if the app is shutdown, and restarted (or a second instance is started), i get this:

> clojure.lang.ExceptionInfo: Conflict! Expected schema#c4353d96 but schema#10b0fe17 was applied.
    expected: "schema#c4353d96"
       found: "schema#10b0fe17"
      reason: :ragtime.strategy/migration-conflict

For the record, it doesn't really matter what strategy I am using. `:apply-new` throws `Table x already exists`, and `:rebase` throws `No implementation of run-down! found for class nil`.  Am I doing something wrong, or is ragtime not able to deal with  app restarts? Many thanks in advance...

**Comment by weavejester** [comment]
Ragtime is reporting that the migration that is applied to the database does not exist on disk. It cannot rebase because the "down" script for the applied migration no longer exists, and therefore it does not know how to revert the migration.

Ragtime keeps migrations in memory, so it will be able to perform rebases even if the migration differs from what's on disk, but only until you restart. Once you restart, the cache of migrations is lost.

I've been considering having Ragtime keep a cache of applied migrations on disk or on the database.

**Comment by dpiliouras** [comment]
Ok, thanks for the explanation. 

For what it's worth, I gave `migratus` a try and it does work as I would have thought (it keeps an `applied` column of type `TIMESTAMP` in the DB). Making a `duct.migrator/migratus` component  out of it was trivial, so it suits our needs.

Thanks again for the prompt reply 👍
