### ISSUE TITLE
Difficult to securely set DB password

### ISSUE THREAD

**Issue by tsmacdonald** [weavejester/ragtime#60]
Our database has a password, which for security reasons I don't want to store raw in `project.clj` or in an environment variable. What I really want is to be able to set the DB password with arbitrary Clojure code, but this is impossible in `project.clj` since most libraries are unavailable. I couldn't find documentation about how to accomplish this—is it possible?

Thanks!

**Comment by michaelklishin** [comment]
We've discussed this in https://github.com/juxt/joplin/issues/14 and https://github.com/juxt/joplin/issues/31. I think we can solve this in Ragtime instead. @martintrojer @weavejester thoughts?

**Comment by weavejester** [comment]
There are two solutions that spring to mind: use a local `profiles.clj` file to store the database connection details out of version control, or use ragtime as a library.

I don't know that Ragtime needs to do any more. I don't see an advantage of using an external resource file over using a local profile.

**Comment by martintrojer** [comment]
Like micheal pointed out, this is been discussed in the joplin project.

I have problem imagining how this would work with either ragtime/joplin.

If you use it as a library there is not problem, because you are in total control of your config. If you are using the lein plugins, like @weavejester says it can be solved with profile.clj. That sounds easier to me than some elaborate new cli commands and ragtime code that will go and hunt for that resource on the file system and/or class path.

**Comment by weavejester** [comment]
Non-issue in version 0.4.0.
